spring:
   application:
    name: back-end-Estacionamiento    
   datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:Ceiba-Estacionamiento;DB_CLOSE_ON_EXIT=FALSE
      jpa:
         show-sql: true
         hibernate:
            ddl-auto: create-drop
         properties:
            hibernate.dialect: org.hibernate.dialect.H2Dialect
   h2:
      console.enabled: true
      console.path: /h2
server:
   port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  