spring:
   datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:file:~/test
      jpa:
         show-sql: true
         hibernate:
            ddl-auto: create-drop
         properties:
            hibernate.dialect: org.hibernate.dialect.H2Dialect
   h2:
      console.enabled: true
      console.path: /h2
server:
   port: 8082
  